package app.newspaper

import app.newspaper.model.Edition
import app.newspaper.model.EditionJson
import app.newspaper.model.WeatherIcon
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Test
import java.io.File
import java.time.LocalDate

class EditionJsonTest {

    // Unit tests run with the module directory as working directory.
    private val fixture = File("../fixtures/sample_edition.json")

    private fun load(): Edition = EditionJson.decodeFromString(Edition.serializer(), fixture.readText())

    @Test
    fun fixtureDeserializesIntoModel() {
        val e = load()
        assertEquals("The First Light", e.masthead.name)
        assertEquals(LocalDate.of(2026, 10, 3), LocalDate.parse(e.masthead.date))
        assertEquals(276, e.masthead.number)
        assertEquals(WeatherIcon.PARTLY_CLOUDY, e.weather?.icon)
        assertEquals(6, e.weather?.hourly?.size)
        assertEquals(0.75, e.weather?.moon?.phase)
        assertEquals(5, e.science?.paragraphs?.size)
        assertNull("QR is generated by the app, not stored", e.science?.qrDataUri)
        assertEquals(2, e.news.india.size)
        assertEquals(2, e.news.world.size)
        assertEquals(5, e.sports.size)
        assertEquals(6, e.schedule.size)
        assertEquals(6, e.tasks.size)
        assertEquals(1, e.birthdays.size)
        assertEquals(3, e.renewals.size)
        assertEquals(12, e.health?.hrTwoHourly?.size)
        assertEquals(12, e.health?.stressTwoHourly?.size)
        assertEquals(13, e.messages.size)
        assertEquals(listOf("WhatsApp", "Signal", "Telegram"), e.messages.map { it.app }.distinct())
        assertNull(e.comic?.imageDataUri)
    }

    @Test
    fun fixtureRoundTrips() {
        val e = load()
        val again = EditionJson.decodeFromString(Edition.serializer(), EditionJson.encodeToString(Edition.serializer(), e))
        assertEquals(e, again)
    }

    @Test
    fun unknownKeysAreRejected() {
        val bad = fixture.readText().replaceFirst("\"masthead\"", "\"mastheed\": {}, \"masthead\"")
        val result = runCatching { EditionJson.decodeFromString(Edition.serializer(), bad) }
        assertTrue("typos in fixtures must fail loudly", result.isFailure)
    }
}
